core: add --temp-dir parameter to jagen-spawn

diff --git a/bin/jagen-spawn b/bin/jagen-spawn
--- a/bin/jagen-spawn
+++ b/bin/jagen-spawn
@@ -6,15 +6,28 @@ else
     echo "Warning: SSH_AUTH_SOCK is not set, not forwarding SSH agent"
 fi
 
-if [ "$1" = "--work-dir" ]; then
-    work_dir=$(realpath "$2")
-    shift 2
-fi
+while [ "$1" ]; do
+    case $1 in
+        --work-dir)
+            work_dir=$(realpath "$2")
+            shift 2
+            ;;
+        --temp-dir)
+            temp_dir=$(realpath "$2")
+            shift 2
+            ;;
+        *)
+            echo "Error: unknown argument: $1"
+            exit 1
+            ;;
+    esac
+done
 
 exec docker run -it --rm --privileged \
     --env SSH_AUTH_SOCK=$SSH_AUTH_SOCK \
     ${sock_dir:+--volume "$sock_dir:$sock_dir"} \
     ${work_dir:+--volume "$work_dir:/mnt/src/jagen"} \
+    ${temp_dir:+--volume "$temp_dir:/mnt/tmp"} \
     --volume /tmp/build:/tmp/build \
     --volumes-from build-data \
     build "$@"
