Implement creating local root for current project
jagen command wrapper now implements part of the init and cat create a build root for the local project.

diff --git a/bin/jagen b/bin/jagen
--- a/bin/jagen
+++ b/bin/jagen
@@ -1,9 +1,65 @@
 #!/bin/sh
 
-if ! [ "$jagen_root_dir" ]; then
-    echo "This script just forwards its arguments to the currently sourced \
-Jagen project's runner and by itself does nothing."
-    exit 22
+set -eu
+
+: ${jagen_root_dir:=jagen-root}
+: ${jagen_dir=$jagen_root_dir/.jagen}
+
+jagen_url="${jagen_url:-https://github.com/bazurbat/jagen.git}"
+env_file="env.sh"
+runner_script="jagen"
+
+say() {
+    echo "jagen: $*"
+}
+
+die() {
+    say "$*" >&2
+    exit 1
+}
+
+need_cmd() {
+    if ! $(command -v "$1" >/dev/null); then
+        die "could not find the '$1' command"
+    fi
+}
+
+git_clone() {
+    local url="${1:?}" dir="${2:?}"
+    if ! [ -d "$dir" ]; then
+        need_cmd git
+        git clone --depth 1 -- "$url" "$dir"
+    fi
+}
+
+write_env() {
+    cat >"$env_file" <<EOF
+#!/bin/sh
+
+jagen_dir='$jagen_dir'
+jagen_root_dir='$(pwd -P)'
+export jagen_dir jagen_root_dir
+
+. "\$jagen_dir/env.sh"; sts=\$?
+if [ \$sts != 0 ]; then
+    echo "Error: failed to load jagen environment"
+    return \$sts
 fi
 
-exec "$jagen_root_dir/jagen" "$@"
+add_PATH "\$jagen_dir/bin"
+add_PATH "\$jagen_root_dir/bin"
+EOF
+}
+
+main() {
+    jagen_project_dir=$(pwd -P)
+    [ -d "$jagen_root_dir" ] || mkdir "$jagen_root_dir"
+    git_clone "$jagen_url" "$jagen_dir"
+    jagen_dir=$(cd "$jagen_dir" 2>&- && pwd -P)
+    cd "$jagen_root_dir"
+    [ -f "$env_file" ] || write_env
+    . "./$env_file" || return
+    _jagen "$@"
+}
+
+main "$@"
