More robust interrupt and exit cleanup handling
- Download cleanup trap was overriding generic stage cleanup which was
  leaving fifo files laying around after an exit.
- Immediate exit on SIGINT sometimes lead to strange interaction with
  pkg_run exit logging logic.
- Also with 'progress' mode when exit handler tried to write to pipe it
  just silently failed and cleanup was never completed.

Now cleanup function of jagen-stage handles all exit logic. Tested with
various combinations of progress options and interrupting builds and
downloads and it looks like all temporary files are deleted as expected.

diff --git a/bin/jagen-stage b/bin/jagen-stage
--- a/bin/jagen-stage
+++ b/bin/jagen-stage
@@ -16,21 +16,36 @@ pkg__stamp_name="${pkg_name}:${pkg_stage}${pkg_config:+:${pkg_config}}"
 pkg__stamp_file="${jagen_build_dir:?}/${pkg__stamp_name}"
 pkg__log_file="${jagen_log_dir:?}/${pkg__stamp_name}.log"
 
+exec 3>&1
 : >"$pkg__log_file"
 
 _on_exit() {
+    # The tee is not running at this point and writing to pipe causes silent
+    # failure after a few attempts and the current shell will just exit without
+    # finishing the cleanup. We need to redirect the rest of the cleanup output
+    # back to a log file to avoid this.
     if [ "$pkg__pipe" ]; then
-        rm -f "$pkg__pipe"
+        exec >>"$pkg__log_file" 2>&1
+        pkg__rm "$pkg__pipe"
     fi
+
+    pkg__download_cleanup
+
     if [ -z "$jagen__stage_quiet" -a -z "$jagen__stage_verbose" ]; then
         if [ "$pkg__run_last_error" != 0 ] && ! in_list "$pkg__log_file" $jagen__cmd_logs; then
+            # In the case when the output is buffered by ninja and the command
+            # was interrupted the output will be discarded and cat will not
+            # print anything. This is actually what we want in this case.
             cat "$pkg__log_file" 1>&3
         fi
     fi
     [ $pkg__run_last_error = 0 ] || exit $pkg__run_last_error
 }
 
-trap 'exit 2' INT
+# Do not allow to interrupt the stage. Commands running through pkg_run will
+# still receive SIGINT and expected to exit with non zero status (usually 130)
+# which pkg_run will recognise and call exit by itself.
+trap : INT
 trap _on_exit EXIT
 
 if [ -z "${pkg__interactive-}" ]; then
@@ -40,9 +55,9 @@ if [ -z "${pkg__interactive-}" ]; then
         # no need to save a pid and kill tee manually because it finishes when
         # the current shell closes the pipe on exit
         tee <"$pkg__pipe" -a "$pkg__log_file" &
-        exec 1>"$pkg__pipe" 2>&1
+        exec >"$pkg__pipe" 2>&1
     else
-        exec 3>&1 1>>"$pkg__log_file" 2>&1
+        exec >>"$pkg__log_file" 2>&1
     fi
 fi
 
