Print message when failed to load jagen environment, pass error to parent shell

diff --git a/init-root b/init-root
--- a/init-root
+++ b/init-root
@@ -55,11 +55,14 @@ else
     jagen_root="$real_root"
 fi
 
-jagen_build_root="\$PWD"
+export jagen_root
+export jagen_build_root="\$PWD"
 
-export jagen_root jagen_build_root
-
-. "\$jagen_root/lib/env.sh" || return \$?
+. "\$jagen_root/lib/env.sh"; sts=\$?
+if [ \$sts != 0 ]; then
+    echo "Failed to load jagen environment"
+    return \$sts
+fi
 
 add_PATH "\$pkg_private_dir/bin"
 add_PATH "\$jagen_root/bin"
