init-project: wrap toplevel logic in a function

diff --git a/init-project b/init-project
--- a/init-project
+++ b/init-project
@@ -264,75 +264,79 @@ parse_command_line() {
     done
 }
 
-if [ $# = 0 ]; then
-    show_usage; exit 0
-fi
-
-parse_command_line "$@"
-
-if [ -z "${use_force-}" -a "$(printf *)" != '*' ]; then
-    die "not initializing non-empty directory without force"
-fi
-
-if [ "${jagen_product-}" ]; then
-    jagen_product_dir="$jagen_dir/usr/product/$jagen_product"
-    [ -d "$jagen_product_dir" ] ||
-        die "product '$jagen_product' was not found in $(dirname "$jagen_product_dir")"
-fi
-
-if [ "${share_sources-}" ]; then
-    jagen_src_dir='$jagen_project_dir/../src'
-else
-    jagen_src_dir='$jagen_project_dir/src'
-fi
-
-if [ "${share_dist-}" ]; then
-    jagen_dist_dir='$jagen_project_dir/../dist'
-else
-    jagen_dist_dir='$jagen_project_dir/dist'
-fi
-
-if [ "${share_toolchains-}" ]; then
-    jagen_toolchains_dir='$jagen_project_dir/../toolchains'
-else
-    jagen_toolchains_dir='$jagen_project_dir/toolchains'
-fi
-
 on_layer_init_error() {
     message "layer '$layer' init failed with status: $?"
 }
 
-trap on_layer_init_error EXIT
-
-for layer in ${jagen_product_dir-} $init_jagen_layers; do
-    if [ -f "$layer/init.sh" ]; then
-        . "$layer/init.sh"
+do_init() {
+    if [ $# = 0 ]; then
+        show_usage; exit 0
     fi
-done
 
-trap - EXIT
+    parse_command_line "$@"
 
-# prepend jagen_layers in case it was set by layer init (product)
-init_jagen_layers="$jagen_layers $init_jagen_layers"
+    if [ -z "${use_force-}" -a "$(printf *)" != '*' ]; then
+        die "not initializing non-empty directory without force"
+    fi
 
-# construct newline-separated list of layers -- it looks prettier in
-# the config and allows having spaces in the paths
-jagen_layers="
+    if [ "${jagen_product-}" ]; then
+        jagen_product_dir="$jagen_dir/usr/product/$jagen_product"
+        [ -d "$jagen_product_dir" ] ||
+            die "product '$jagen_product' was not found in $(dirname "$jagen_product_dir")"
+    fi
+
+    if [ "${share_sources-}" ]; then
+        jagen_src_dir='$jagen_project_dir/../src'
+    else
+        jagen_src_dir='$jagen_project_dir/src'
+    fi
+
+    if [ "${share_dist-}" ]; then
+        jagen_dist_dir='$jagen_project_dir/../dist'
+    else
+        jagen_dist_dir='$jagen_project_dir/dist'
+    fi
+
+    if [ "${share_toolchains-}" ]; then
+        jagen_toolchains_dir='$jagen_project_dir/../toolchains'
+    else
+        jagen_toolchains_dir='$jagen_project_dir/toolchains'
+    fi
+
+    trap on_layer_init_error EXIT
+
+    for layer in ${jagen_product_dir-} $init_jagen_layers; do
+        if [ -f "$layer/init.sh" ]; then
+            . "$layer/init.sh"
+        fi
+    done
+
+    trap - EXIT
+
+    # prepend jagen_layers in case it was set by layer init (product)
+    init_jagen_layers="$jagen_layers $init_jagen_layers"
+
+    # construct newline-separated list of layers -- it looks prettier in
+    # the config and allows having spaces in the paths
+    jagen_layers="
 "
-for layer in $init_jagen_layers; do
-    jagen_layers="$jagen_layers$layer
+    for layer in $init_jagen_layers; do
+        jagen_layers="$jagen_layers$layer
 "
-done
+    done
 
-write_env || exit
-write_config "$config_file" || exit
+    write_env || exit
+    write_config "$config_file" || exit
 
-if ! [ -f "lib/rules.lua" ]; then
-    mkdir -p lib
-    cat >"lib/rules.lua" <<EOF
+    if ! [ -f "lib/rules.lua" ]; then
+        mkdir -p lib
+        cat >"lib/rules.lua" <<EOF
 -- local rules for $(basename "$PWD")
 EOF
 fi
 
-. ./env.sh || exit
-jagen refresh
+    . ./env.sh || exit
+    jagen refresh
+}
+
+do_init "$@"
