Allow specifying multiple items for init-project, add some validation

diff --git a/init-project b/init-project
--- a/init-project
+++ b/init-project
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+set -eu
+
 env_file="env.sh"
 config_file="config.sh"
 
@@ -119,7 +121,9 @@ write_config() {
 # jagen_dir         - refers to the jagen source directory
 # jagen_project_dir - refers to the current project directory
 
-# Layers used by this project.
+# A list of directories containing layers used by this project.
+# NOTE: separate items with newlines (\\n) or tabs (\\t), spaces ( ) are
+# assumed to be part of the pathname, so the indentation will be counted too.
 jagen_layers="$jagen_layers"
 
 # Toplevel working directory.
@@ -153,15 +157,25 @@ jagen_build_profile="release"
 EOF
 }
 
-parse_name() {
-    local name="$1"
+parse_names() {
+    local i=
 
-    # if an argument does not contain '/' it will remain unchanged;
-    # otherwise it will become empty after the substitution
-    if [ "${name%%*/*}" = "$name" ]; then
-        jagen_product="$name"
+   for i in "$@"; do
+        if [ "$i" = . ] || [ "$i" = .. ]; then
+            die "invalid layer path value '$i'"
+        fi
+    done
+
+    if [ $# -gt 1 ]; then
+        init_jagen_layers="$@"
     else
-        jagen_product_dir="$name"
+        # if an argument does not contain '/' it will remain unchanged;
+        # otherwise it will become empty after the substitution
+        if [ "${1%%*/*}" = "$1" ]; then
+            jagen_product="$1"
+        else
+            init_jagen_layers="$1"
+        fi
     fi
 }
 
@@ -170,7 +184,7 @@ parse_command_line() {
 
     while [ $# -gt 0 ]; do
         if [ "$eoa" ]; then
-            parse_name "$1"
+            parse_names "$@"
             break
         else
             case $1 in
@@ -191,7 +205,7 @@ parse_command_line() {
                     fi
                     shift ;;
                  *) eoa=1
-                    parse_name "$1"
+                    parse_names "$@"
                     break ;;
             esac
         fi
@@ -203,6 +217,8 @@ jagen_dir=$(dirname $0)
 jagen_project_dir=''
 jagen_product=''
 jagen_flags=''
+jagen_layers=
+init_jagen_layers=
 
 if [ $# = 0 ]; then
     show_help
@@ -215,39 +231,41 @@ if [ -z "$use_force" -a "$(printf *)" != '*' ]; then
     die "not initializing non-empty directory without force"
 fi
 
-if ! [ "$jagen_product_dir" ]; then
-    if ! [ "$jagen_product" ]; then
-        message "no product specified, assuming default native build"
-        jagen_product='default'
-    fi
-
+if [ "$jagen_product" ]; then
     jagen_product_dir="$jagen_dir/usr/product/$jagen_product"
+    [ -d "$jagen_product_dir" ] ||
+        die "product '$jagen_product' was not found in $(dirname "$jagen_product_dir")"
 
-    if ! [ -d "$jagen_product_dir" ]; then
-        die "product '$jagen_product' was not found in $(dirname $jagen_product_dir)"
-    fi
-else
-    if ! [ -d "$jagen_product_dir" ]; then
-        die "the specified product directory '$jagen_product_dir' is not exists"
-    fi
+    init_jagen_layers="$jagen_product_dir"
 fi
 
-if [ "$share_sources" ]; then
+if [ "${share_sources-}" ]; then
     jagen_src_dir='$jagen_root_dir/src'
 else
     jagen_src_dir='$jagen_project_dir/src'
 fi
 
-if [ -f "$jagen_product_dir/init.sh" ]; then
-    . "$jagen_product_dir/init.sh" ||
-        die "project init failed with status: $?"
-fi
+on_layer_init_error() {
+    message "layer '$layer' init failed with status: $?"
+}
 
-# assume the directory of the product itself as the sole layer by default
-if [ -z "$jagen_layers" ]; then
-    jagen_layers="
-$(real_path "$jagen_product_dir")
+trap on_layer_init_error EXIT
+
+for layer in $init_jagen_layers; do
+    if [ -f "$layer/init.sh" ]; then
+        . "$layer/init.sh" ||
+            die "layer '$layer' init failed with status: $?"
+    fi
+done
+
+trap - EXIT
+
+if ! [ "$jagen_layers" ] && [ "$init_jagen_layers" ]; then
+    jagen_layers=$(printf '\n '); jagen_layers=${jagen_layers% }
+    for layer in $init_jagen_layers; do
+        jagen_layers="$jagen_layers$(printf '%s\n' "$layer")
 "
+    done
 fi
 
 write_env || exit
